INSERT INTO ROLE VALUES(1,'USER_BASIC')
INSERT INTO ROLE VALUES(2,'USER_GOLD')
INSERT INTO ROLE VALUES(3,'USER_PLATINUM')
INSERT INTO ROLE VALUES(4,'USER_BLACK')


INSERT INTO CATEGORY VALUES(1,'Eletrônicos e celulares',true)
INSERT INTO CATEGORY VALUES(2,'Carros',false)